apiVersion: v1
kind: Service
metadata:
  name: adaptive-app
  namespace: adaptive-logging
spec:
  selector:
    app: adaptive-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
